#!/usr/bin/env python3
"""
mkape.py - Create an Actually Portable Executable (APE) from Linux ELF binaries.

This is a minimal reimplementation of apelink for environments where the
Cosmopolitan toolchain's APE binaries cannot run (e.g., gVisor sandboxes).

It creates a polyglot file that:
  - Starts with a shell script that detects the architecture and executes
    the appropriate embedded ELF binary via the APE loader
  - Contains embedded ELF binaries for x86_64 and aarch64
  - Works on Linux systems with the APE loader or via the shell fallback

Usage:
    python3 mkape.py -o output.com \
        --x86_64 path/to/x86_64-elf \
        --aarch64 path/to/aarch64-elf \
        [--ape-loader-x86_64 path/to/ape-x86_64.elf] \
        [--ape-loader-aarch64 path/to/ape-aarch64.elf]
"""

import argparse
import os
import struct
import sys
import hashlib
import tempfile
import zipfile
import io


def align(n, alignment):
    return (n + alignment - 1) & ~(alignment - 1)


def make_shell_header(x86_offset, x86_size, aarch64_offset, aarch64_size):
    """Create a shell script header that extracts and runs the right binary."""
    # The shell script detects architecture and extracts the appropriate ELF
    # Use tail+head for fast extraction (avoids dd bs=1 which is byte-at-a-time)
    # tail -c +N reads from byte N onward (1-indexed), head -c M takes first M bytes
    script = f'''#!/bin/sh
# Actually Portable Executable - Geist
# Generated by mkape.py
p="$0"
a=$(uname -m)
t="${{TMPDIR:-/tmp}}/.geist-$$"
trap 'rm -f "$t"' EXIT
case "$a" in
x86_64|amd64) tail -c +{x86_offset + 1} "$p" | head -c {x86_size} >"$t";;
aarch64|arm64) tail -c +{aarch64_offset + 1} "$p" | head -c {aarch64_size} >"$t";;
*) echo "Unsupported: $a" >&2; exit 1;;
esac
chmod +x "$t"
exec "$t" "$@"
'''
    return script.encode('ascii')


def make_ape(x86_64_path, aarch64_path, output_path,
             ape_loader_x86_64=None, ape_loader_aarch64=None):
    """Create an APE binary from two ELF binaries."""

    with open(x86_64_path, 'rb') as f:
        x86_data = f.read()
    with open(aarch64_path, 'rb') as f:
        aarch64_data = f.read()

    # Verify they're ELF binaries
    assert x86_data[:4] == b'\x7fELF', f"{x86_64_path} is not an ELF"
    assert aarch64_data[:4] == b'\x7fELF', f"{aarch64_path} is not an ELF"

    # Create a temporary header to calculate offsets
    # Shell header + padding + x86_64 ELF + padding + aarch64 ELF
    ALIGNMENT = 4096  # Page-align the ELFs for mmap efficiency

    # First pass: estimate header size
    dummy_header = make_shell_header(0, 0, 0, 0)
    header_size = align(len(dummy_header) + 1, ALIGNMENT)  # +1 for newline

    x86_offset = header_size
    x86_size = len(x86_data)

    aarch64_offset = align(x86_offset + x86_size, ALIGNMENT)
    aarch64_size = len(aarch64_data)

    # Second pass: create real header with correct offsets
    header = make_shell_header(x86_offset, x86_size, aarch64_offset, aarch64_size)
    # Ensure header fits in our allocated space
    assert len(header) < header_size, "Header too large"

    # Build the output
    output = bytearray()

    # Shell header, padded to alignment
    output.extend(header)
    output.extend(b'\n' * (header_size - len(header)))

    # x86_64 ELF
    assert len(output) == x86_offset
    output.extend(x86_data)

    # Pad to alignment
    output.extend(b'\0' * (aarch64_offset - len(output)))

    # aarch64 ELF
    assert len(output) == aarch64_offset
    output.extend(aarch64_data)

    # Write output
    with open(output_path, 'wb') as f:
        f.write(output)
    os.chmod(output_path, 0o755)

    total_size = len(output)
    print(f"Created APE binary: {output_path}")
    print(f"  Total size:    {total_size:,} bytes ({total_size / 1048576:.1f} MB)")
    print(f"  x86_64:        offset=0x{x86_offset:x}, size={x86_size:,} bytes")
    print(f"  aarch64:       offset=0x{aarch64_offset:x}, size={aarch64_size:,} bytes")

    return total_size


def main():
    parser = argparse.ArgumentParser(description='Create an APE from Linux ELF binaries')
    parser.add_argument('-o', '--output', required=True, help='Output APE file path')
    parser.add_argument('--x86_64', '--x86-64', required=True, help='x86_64 ELF binary')
    parser.add_argument('--aarch64', required=True, help='aarch64 ELF binary')
    parser.add_argument('--ape-loader-x86_64', help='APE loader for x86_64 (optional)')
    parser.add_argument('--ape-loader-aarch64', help='APE loader for aarch64 (optional)')

    args = parser.parse_args()

    if not os.path.isfile(args.x86_64):
        sys.exit(f"Error: x86_64 binary not found: {args.x86_64}")
    if not os.path.isfile(args.aarch64):
        sys.exit(f"Error: aarch64 binary not found: {args.aarch64}")

    make_ape(args.x86_64, args.aarch64, args.output,
             args.ape_loader_x86_64, args.ape_loader_aarch64)


if __name__ == '__main__':
    main()
